#!/bin/sh
sed -i $'s/${vendorid:+-V "$vendorid"}/${vendorid:+-V \'\' "-x 0x3c:$vendorid"}/g' /lib/netifd/proto/dhcp.sh
chmod +x -R /etc/scripts/*
chmod +x -R /etc/init.d/*
echo "PATH=$PATH:/etc/scripts" >> /etc/profile
source /etc/profile
echo "public:$(openssl passwd 123456)" >/etc/nginx/webdavpasswd
echo "0 0 * * 0 /etc/scripts/updateAD" >> /etc/crontabs/root
uci set nginx.global.uci_enable='false'
uci commit
/etc/init.d/nginx reload
exit 0