#!/bin/sh

curl --connect-timeout 15 'https://raw.githubusercontent.com/zcy85611/dnsmasq_rules/main/gfwlist.conf' > /tmp/gfwlist.conf
content_length=$(curl -sI 'https://raw.githubusercontent.com/zcy85611/dnsmasq_rules/main/gfwlist.conf' | grep -i Content-Length | awk '{print $2}' | tr -d '\r')
local_size=$(wc -c < /tmp/gfwlist.conf)
echo $content_length $local_size
if [ "$content_length" != "$local_size" ]; then
    echo "incomplete download, abort"
    rm -rf /tmp/gfwlist.conf
else
   mv -f /tmp/gfwlist.conf /etc/dnsmasq.d
fi

curl --connect-timeout 15 -o /tmp/ip_cn 'https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt'
content_length=$(curl -sI 'https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt' | grep -i Content-Length | awk '{print $2}' | tr -d '\r')
local_size=$(wc -c < /tmp/ip_cn)
echo $content_length $local_size
if [ "$content_length" != "$local_size" ]; then
    echo "incomplete download, abort"
    rm -rf /tmp/ip_cn
else
	echo "define ip_cnv4 = {" > /etc/dline/ip_cnv4
	awk '{print $0 ","}' /tmp/ip_cn >> /etc/dline/ip_cnv4
	sed -i '$a}' /etc/dline/ip_cnv4
	rm -rf /tmp/ip_cn
fi

/etc/init.d/dline restart
/etc/init.d/dnsmasq restart
