#!/bin/sh /etc/rc.common
# Copyright (C) 2020-2022 Leo Zhao <skygunner5@hotmail.com>
# Licensed to the public under the Apache License 2.0.

START=99
USE_PROCD=1
UU_BIN="/usr/share/uugamebooster/uuplugin"
UU_CONF="/usr/share/uugamebooster/uu.conf"
UU_LOGFILE="/tmp/uugamebooster.log"

get_basic() {
	config_get_bool enabled $1 enabled '0'
	}

start_service() {
	config_load uuplugin
	config_foreach get_basic basic
	[ $enabled != 1 ] && return 1
    procd_open_instance
    procd_set_param command $UU_BIN $UU_CONF >$UU_LOGFILE 2>&1
    procd_set_param respawn
 	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/uuplugin
    procd_close_instance
}

reload_service()
{
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "uuplugin"
}